name: Build PhantomFinal APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip -o "*.zip" -d appsrc
          ls -R appsrc

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Gradle permissions
        working-directory: appsrc
        run: chmod +x gradlew

      - name: Build APK
        working-directory: appsrc
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Built-APK
          path: appsrc/app/build/outputs/apk/debug/*.apk
